version: "3"
services:
  app:
    container_name: rally-meteor
    restart: always
    volumes:
        - .:/home/meteor/app/
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ../mongoDB/rally:/data/db
    ports:
      - "27017:27017"
